import itertools

numbers = {
        'x' : '0',
        'y' : '1',
        'z' : '2',
        'w' : '3',
        '0' : '-2',
        '1' : '-3'
        }

def swiz(len):
    retval = []
    for s in itertools.product('xyzw01', repeat=len):
        nums = ','.join([ numbers[x] for x in s ])
        retval.append("#define s_{0} swizzle<{1}>()".format(
            "".join(s), nums))
    return retval

if __name__ == '__main__':
    print ('''
#pragma once

// Autogenerated using MakeVectorSwizzle.py

''')
    for s in swiz(2):
        print(s)
    for s in swiz(3):
        print(s)
    for s in swiz(4):
        print(s)

